function plotResults(Elem)
% PLOTRESULTS Plots BEMT results along the blade (forces, inflow, aoa).
% -----
%
% Synopsis: [-] = PLOTRESULTS(Elem)
%
% Input:    Elem = (required) Every data related to blade elements (chords, pitch,...)
%
% Output:   6 Figures (dT, dCT, dL & dD, dcl & dcd, lambda, AOA).
%
% Calls:    none
%
% See also: BEMT.

% ------
% This script is an optional part of the BEMT code.
% Author: Thomas Lambert <t.lambert@uliege.be>
% ULiege - Aeroelasticity and Experimental Aerodynamics
% MIT License
% https://gitlab.uliege.be/thlamb/bemt
% -------------------------------------------------------------------------


figname='Thrust - spanwise distributation';
figure('PaperUnits', 'inches', 'PaperPosition', [0 0 1280 1024]/250,'Name',figname)
hold on
plot(Elem.r,Elem.dT,'linewidth',1.2)
grid on
hXLabel=xlabel('r [-]');
hYLabel=ylabel('$dT$ [N]');
hTitle=title('Thrust spanwise distribution');
set(gca, 'FontName','Helvetica');
set(gca, 'Fontsize', 14);
set([hXLabel, hYLabel, hTitle], 'interpreter','latex', 'Fontsize', 14);
set(gca,...
    'Box', 'off',...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'XColor'      , 'k', ...
    'YColor'      , 'k', ...
    'GridLineStyle', ':'         , ...
    'GridColor', 'k', ...
    'GridAlpha', 0.25, ...
    'LineWidth'   , 1         );
set(gcf, 'PaperPositionMode', 'auto');

figname='Thrust coefficient - spanwise distributation';
figure('PaperUnits', 'inches', 'PaperPosition', [0 0 1280 1024]/250,'Name',figname)
hold on
plot(Elem.r,Elem.dCT,'linewidth',1.2)
grid on
hXLabel=xlabel('r [-]');
hYLabel=ylabel('$C_t$ [-]');
hTitle=title('Thrust coefficient spanwise distribution');
set(gca, 'FontName','Helvetica');
set(gca, 'Fontsize', 14);
set([hXLabel, hYLabel, hTitle], 'interpreter','latex', 'Fontsize', 14);
set(gca,...
    'Box', 'off',...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'XColor'      , 'k', ...
    'YColor'      , 'k', ...
    'GridLineStyle', ':'         , ...
    'GridColor', 'k', ...
    'GridAlpha', 0.25, ...
    'LineWidth'   , 1         );
set(gcf, 'PaperPositionMode', 'auto');


figname='Forces - spanwise distributation';
figure('PaperUnits', 'inches', 'PaperPosition', [0 0 1280 1024]/250,'Name',figname)
hold on
plot(Elem.r,Elem.dL,'linewidth',1.2)
plot(Elem.r,Elem.dD,'linewidth',1.2)
grid on
hLegend=legend('Lift','Drag','Location','NorthWest');
hXLabel=xlabel('r [-]');
hYLabel=ylabel('$dL\mbox{ and }dD$ [-]');
hTitle=title('Lift and Drag spanwise distribution');
set(gca, 'FontName','Helvetica');
set(gca, 'Fontsize', 14);
set([hXLabel, hYLabel, hLegend, hTitle], 'interpreter','latex', 'Fontsize', 14);
set(gca,...
    'Box', 'off',...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'XColor'      , 'k', ...
    'YColor'      , 'k', ...
    'GridLineStyle', ':'         , ...
    'GridColor', 'k', ...
    'GridAlpha', 0.25, ...
    'LineWidth'   , 1         );
set(gcf, 'PaperPositionMode', 'auto');


figname='Forces coeff - spanwise distributation';
figure('PaperUnits', 'inches', 'PaperPosition', [0 0 1280 1024]/250,'Name',figname)
hold on
plot(Elem.r,Elem.cl,'linewidth',1.2)
plot(Elem.r,Elem.cd,'linewidth',1.2)
grid on
hLegend=legend('Lift','Drag','Location','NorthWest');
hXLabel=xlabel('r [-]');
hYLabel=ylabel('$C_l\mbox{ and }C_d$ [-]');
hTitle=title('Lift and Drag spanwise distribution');
set(gca, 'FontName','Helvetica');
set(gca, 'Fontsize', 14);
set([hXLabel, hYLabel, hLegend, hTitle], 'interpreter','latex', 'Fontsize', 14);
set(gca,...
    'Box', 'off',...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'XColor'      , 'k', ...
    'YColor'      , 'k', ...
    'GridLineStyle', ':'         , ...
    'GridColor', 'k', ...
    'GridAlpha', 0.25, ...
    'LineWidth'   , 1         );
set(gcf, 'PaperPositionMode', 'auto');




% Plot the local inflow along the blade
% -------------------------------------------------------------------------
figname='Inflow - spanwise distributation';
figure('PaperUnits', 'inches', 'PaperPosition', [0 0 1280 1024]/250,'Name',figname)
plot(Elem.r,Elem.Lambda,'linewidth',1.2)
grid on
hXLabel=xlabel('r [-]');
hYLabel=ylabel('$\lambda$ [-]');
hTitle=title('Inflow spanwise distribution');
set(gca, 'FontName','Helvetica');
set(gca, 'Fontsize', 14);
set([hXLabel, hYLabel, hTitle], 'interpreter','latex', 'Fontsize', 14);
set(gca,...
    'Box', 'off',...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'XColor'      , 'k', ...
    'YColor'      , 'k', ...
    'GridLineStyle', ':'         , ...
    'GridColor', 'k', ...
    'GridAlpha', 0.25, ...
    'LineWidth'   , 1         );
set(gcf, 'PaperPositionMode', 'auto');




% Plot the locl effective angle of attack along the blade
% -------------------------------------------------------------------------
figname='True AOA - spanwise distributation';
figure('PaperUnits', 'inches', 'PaperPosition', [0 0 1280 1024]/250,'Name',figname)
plot(Elem.r,radtodeg(Elem.AOA),'linewidth',1.2)
grid on
hXLabel=xlabel('r [-]');
hYLabel=ylabel('$\alpha$ [deg]');
hTitle=title('Effective AOA spanwise distribution');
set(gca, 'FontName','Helvetica');
set(gca, 'Fontsize', 14);
set([hXLabel, hYLabel, hTitle], 'interpreter','latex', 'Fontsize', 14);
set(gca,...
    'Box', 'off',...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'XColor'      , 'k', ...
    'YColor'      , 'k', ...
    'GridLineStyle', ':'         , ...
    'GridColor', 'k', ...
    'GridAlpha', 0.25, ...
    'LineWidth'   , 1         );
set(gcf, 'PaperPositionMode', 'auto');


end
